### ISSUE TITLE
这么好用的插件真的没人发现吗！

### ISSUE THREAD

**Issue by emosheeep** [liuweiGL/vite-plugin-demand-import#2]
苍天饶过谁，终于是逃过了babel和unplugin-vue-components，我们的项目因为是老项目迁移vite，有的东西还是得用类似babel-plugin-component插件那样的写法才能兼容，找了半天才找到这个插件。兄弟感觉你需要做一波推广啊，我这不惜晚点下班也要来说两句，还有就是你那个包也不把仓库链接放上，GitHub源我找了半天才找到！

**Comment by liuweiGL** [comment]
谢谢
