### ISSUE TITLE
TypeError: demandImport is not a function

### ISSUE THREAD

**Issue by cuiliangl** [liuweiGL/vite-plugin-demand-import#3]
![image](https://github.com/liuweiGL/vite-plugin-demand-import/assets/25759364/f353defa-25dd-4d0a-a542-4be16f2918f9)
![image](https://github.com/liuweiGL/vite-plugin-demand-import/assets/25759364/bc06495e-0050-4b44-932c-14d1a28ea5a7)
![image](https://github.com/liuweiGL/vite-plugin-demand-import/assets/25759364/f89bf33d-1f72-4ec4-a719-d99229575fd0)

**Comment by liuweiGL** [comment]
别用这个库了，vite 自身就支持按需导入，css 的话直接引用全量包吧，没必要为了一点点性能搞的这么麻烦
